### ISSUE TITLE
您好，貌似运行不起来

### ISSUE THREAD

**Issue by a646465071** [zidanfanshao/vcenter_tools#1]
11月 13, 2024 9:41:26 上午 com.sun.javafx.application.PlatformImpl startup
警告: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @75914189'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by zidanfanshao** [comment]
看报错应该是你环境的问题，说下运行环境，我测测

**Comment by a646465071** [comment]
java 11.0.21

**Comment by zidanfanshao** [comment]
这个java版本可以正常运行的，那个报错gpt说是javafx渲染方面的，建议你运行时加
-Dprism.order=sw -Dprism.native=false之类的参数来禁用硬件加速，使用软件渲染或者修改虚拟机配置进行尝试！祝你好运🤞
![image](https://github.com/user-attachments/assets/c08c9b40-49a1-467f-84f1-02e2bd85d7ab)

**Comment by 0neOfU4** [comment]
> java 11.0.21

重新用java8编译就好了，java8自带javafx，往上的版本需要单独安装javafx

**Comment by zidanfanshao** [comment]
> > java 11.0.21
> 
> 
> 
> 重新用java8编译就好了，java8自带javafx，往上的版本需要单独安装javafx

当然👍，这也是一种方法
